import "./globals.css";
import { roboto } from "@/utils/fonts";

export const metadata = {
  title: "Rayhana & Rahmad's Wedding",
  description: "Generated by create next app",
  image: "/favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
